[build.environment]
DART_SASS_VERSION = "1.87.0"
GO_VERSION = "1.24.2"
HUGO_VERSION = "0.147.3"
NODE_VERSION = "22"
TZ = "Asia/Jakarta"
GIT_SUBMODULE_STRATEGY = "recursive"

[build]
publish = "public"
command = """\
  curl -LJO https://github.com/sass/dart-sass/releases/download/1.87.0/dart-sass-1.87.0-linux-x64.tar.gz && \
  tar -xf dart-sass-1.87.0-linux-x64.tar.gz && \
  rm dart-sass-1.87.0-linux-x64.tar.gz && \
  export PATH=/opt/build/repo/dart-sass:$PATH && \
  git config core.quotepath false && \
  hugo --gc --minify \
  """